export const examsB = [
  {
    slug: "czy-w-tej-sytuacji-masz-obowiazek-zastosowac-sie-do-znaku-stop-id-pytania-3688",
    isActive: true,
    id: "id3688",
    text: 'Czy w tej sytuacji masz obowiązek zastosować się do znaku "STOP"?',
    a: "",
    b: "",
    c: "",
    r: "n",
    media: "D26_184org.png",
    categories: ["a", "b", "c", "d", "t", "am", "a1", "a2", "b1", "c1", "d1"],
    score: 3,
  },
  {
    slug: "czy-po-zatrzymaniu-pojazdu-do-kontroli-kierujacy-pojazdem-moze-z-niego-wysiasc-bez-pozwolenia-kontrolujacego-id-pytania-10030",
    isActive: true,
    id: "id10030",
    text: "Czy po zatrzymaniu pojazdu do kontroli, kierujący pojazdem może z niego wysiąść bez pozwolenia kontrolującego?",
    a: "",
    b: "",
    c: "",
    r: "n",
    media: "ktw0067.png",
    categories: ["a", "b", "c", "d", "t", "am", "a1", "a2", "b1", "c1", "d1"],
    score: 2,
  },
  {
    slug: "czy-w-dzien-zabronione-jest-ostrzeganie-swiatlami-drogowymi-jezeli-moze-spowodowac-to-oslepienie-innych-kierujacych-id-pytania-8246",
    isActive: true,
    id: "id8246",
    text: "Czy w dzień zabronione jest ostrzeganie światłami drogowymi, jeżeli może spowodować to oślepienie innych kierujących?",
    a: "",
    b: "",
    c: "",
    r: "t",
    media: "Slajd571_cen_1024x576.png",
    categories: ["b"],
    score: 1,
  },
  {
    slug: "czy-postoj-pojazdu-bezposrednio-za-widocznym-slupkiem-wskaznikowym-jest-zabroniony-id-pytania-12556",
    isActive: true,
    id: "id12556",
    text: "Czy postój pojazdu bezpośrednio za widocznym słupkiem wskaźnikowym jest zabroniony?",
    a: "",
    b: "",
    c: "",
    r: "t",
    media: "1837ztV.mp4",
    categories: ["b"],
    score: 3,
  },
  {
    slug: "czy-w-tym-miejscu-wolno-ci-zmienic-pas-ruchu-na-lewy-id-pytania-7305",
    isActive: true,
    id: "id7305",
    text: "Czy w tym miejscu wolno Ci zmienić pas ruchu na lewy?",
    a: "",
    b: "",
    c: "",
    r: "n",
    media: "3904.mp4",
    categories: ["a", "b", "c", "d", "t", "am", "a1", "a2", "b1", "c1", "d1"],
    score: 1,
  },
  {
    slug: "czy-skrecajac-w-lewo-na-tym-skrzyzowaniu-masz-pierwszenstwo-przed-nadjezdzajacym-z-przeciwka-pojazdem-id-pytania-6089",
    isActive: true,
    id: "id6089",
    text: "Czy skręcając w lewo na tym skrzyżowaniu masz pierwszeństwo przed nadjeżdżającym z przeciwka pojazdem?",
    a: "",
    b: "",
    c: "",
    r: "n",
    media: "1A4108.mp4",
    categories: ["a", "b", "c", "d", "t", "am", "a1", "a2", "b1", "c1", "d1"],
    score: 3,
  },
  {
    slug: "czy-w-tej-sytuacji-musisz-sie-zatrzymac-id-pytania-13162",
    isActive: true,
    id: "id13162",
    text: "Czy w tej sytuacji musisz się zatrzymać?",
    a: "",
    b: "",
    c: "",
    r: "t",
    media: "GM_W9-4.mp4",
    categories: ["a", "b", "c", "d", "t", "am", "a1", "a2", "b1", "c1", "d1"],
    score: 3,
  },
  {
    slug: "czy-w-tej-sytuacji-masz-prawo-przekroczyc-dopuszczalna-predkosc-by-jak-najszybciej-zakonczyc-manewr-wyprzedzania-id-pytania-7411",
    isActive: true,
    id: "id7411",
    text: "Czy w tej sytuacji masz prawo przekroczyć dopuszczalną prędkość, by jak najszybciej zakończyć manewr wyprzedzania?",
    a: "",
    b: "",
    c: "",
    r: "n",
    media: "L2T2_008_b.mp4",
    categories: ["a", "b", "c", "d", "a1", "a2", "b1", "c1", "d1"],
    score: 3,
  },
  {
    slug: "czy-w-razie-unieruchomienia-pojazdu-na-przejezdzie-kolejowym-masz-obowiazek-ostrzec-kierujacego-pojazdem-szynowym-jezeli-nie-jest-mozliwie-usuniecie-pojazdu-z-t-id-pytania-8323",
    isActive: true,
    id: "id8323",
    text: "Czy w razie unieruchomienia pojazdu na przejeździe kolejowym masz obowiązek ostrzec kierującego pojazdem szynowym, jeżeli nie jest możliwie usunięcie pojazdu z tego przejazdu?",
    a: "",
    b: "",
    c: "",
    r: "t",
    media: "Slajd205_cen_1024x576.png",
    categories: ["b"],
    score: 3,
  },
  {
    slug: "poruszasz-sie-z-predkoscia-110-kmh-czy-w-tej-sytuacji-masz-obowiazek-zmniejszyc-predkosc-id-pytania-10513",
    isActive: true,
    id: "id10513",
    text: "Poruszasz się z prędkością 110 km/h. Czy w tej sytuacji masz obowiązek zmniejszyć prędkość?",
    a: "",
    b: "",
    c: "",
    r: "n",
    media: "1704ztV_2.mp4",
    categories: ["b"],
    score: 2,
  },
  {
    slug: "skrecasz-w-lewo-na-skrzyzowaniu-czy-po-wjechaniu-na-jezdnie-poprzeczna-znaki-poziome-pozwalaja-ci-zajac-pas-ruchu-przy-prawej-krawedzi-jezdni-id-pytania-612",
    isActive: true,
    id: "id612",
    text: "Skręcasz w lewo na skrzyżowaniu. Czy po wjechaniu na jezdnię poprzeczną znaki poziome pozwalają Ci zająć pas ruchu przy prawej krawędzi jezdni?",
    a: "",
    b: "",
    c: "",
    r: "t",
    media: "MM_D14_17_org.mp4",
    categories: ["a", "b", "c", "d", "t", "am", "a1", "a2", "b1", "c1", "d1"],
    score: 1,
  },
  {
    slug: "czy-zatrzymujac-na-drodze-ekspresowej-pojazd-ktory-ulegl-awarii-masz-obowiazek-wlaczyc-swiatla-awaryjne-a-w-razie-gdy-nie-jest-w-nie-wyposazony-swiatla-pozycyjn-id-pytania-6300",
    isActive: true,
    id: "id6300",
    text: "Czy zatrzymując na drodze ekspresowej pojazd, który uległ awarii, masz obowiązek włączyć światła awaryjne, a w razie, gdy nie jest w nie wyposażony - światła pozycyjne?",
    a: "",
    b: "",
    c: "",
    r: "t",
    media: "1C109.png",
    categories: ["a", "b", "c", "d", "a1", "a2", "c1", "d1"],
    score: 1,
  },
  {
    slug: "czy-w-przedstawionej-sytuacji-jestes-ostrzegany-o-wlocie-drogi-z-prawej-strony-id-pytania-997",
    isActive: true,
    id: "id997",
    text: "Czy w przedstawionej sytuacji jesteś ostrzegany o wlocie drogi z prawej strony?",
    a: "",
    b: "",
    c: "",
    r: "n",
    media: "IMG_6630d8org.png",
    categories: ["a", "b", "c", "d", "t", "am", "a1", "a2", "b1", "c1", "d1"],
    score: 2,
  },
  {
    slug: "czy-widoczny-na-skrzyzowaniu-sygnal-zielony-oznacza-bezkolizyjny-skret-w-lewo-id-pytania-7142",
    isActive: true,
    id: "id7142",
    text: "Czy widoczny na skrzyżowaniu sygnał zielony oznacza bezkolizyjny skręt w lewo?",
    a: "",
    b: "",
    c: "",
    r: "n",
    media: "1A4304.mp4",
    categories: ["b", "c", "d", "b1", "c1", "d1"],
    score: 3,
  },
  {
    slug: "czy-na-autostradzie-wolno-ci-poruszac-sie-dowolnym-pasem-ruchu-niezaleznie-od-sytuacji-na-drodze-id-pytania-10499",
    isActive: true,
    id: "id10499",
    text: "Czy na autostradzie wolno Ci poruszać się dowolnym pasem ruchu niezależnie od sytuacji na drodze?",
    a: "",
    b: "",
    c: "",
    r: "n",
    media: "1699ztV_2.mp4",
    categories: ["b"],
    score: 2,
  },
  {
    slug: "czy-w-tej-sytuacji-jestes-ostrzegany-zblizaniu-sie-do-znacznego-wzniesienia-drogi-id-pytania-7438",
    isActive: true,
    id: "id7438",
    text: "Czy w tej sytuacji jesteś ostrzegany zbliżaniu się do znacznego wzniesienia drogi?",
    a: "",
    b: "",
    c: "",
    r: "t",
    media: "3548.mp4",
    categories: ["a", "b", "c", "d", "t", "am", "a1", "a2", "b1", "c1", "d1"],
    score: 2,
  },
  {
    slug: "czy-w-tej-sytuacji-wolno-ci-wjechac-za-sygnalizator-jezeli-zatrzymanie-sie-przed-nim-wymaga-gwaltownego-hamowania-id-pytania-7224",
    isActive: true,
    id: "id7224",
    text: "Czy w tej sytuacji wolno Ci wjechać za sygnalizator, jeżeli zatrzymanie się przed nim wymaga gwałtownego hamowania?",
    a: "",
    b: "",
    c: "",
    r: "t",
    media: "1A311.mp4",
    categories: ["a", "b", "c", "d", "t", "a1", "a2", "b1", "c1", "d1"],
    score: 3,
  },
  {
    slug: "czy-przed-wjechaniem-na-tory-nalezy-upewnic-sie-czy-nie-zbliza-sie-pojazd-szynowy-id-pytania-8322",
    isActive: true,
    id: "id8322",
    text: "Czy przed wjechaniem na tory należy upewnić się, czy nie zbliża się pojazd szynowy?",
    a: "",
    b: "",
    c: "",
    r: "t",
    media: "Slajd290_cen_1024x576.png",
    categories: ["b"],
    score: 3,
  },
  {
    slug: "czy-na-drodze-jednokierunkowej-cofanie-jest-zabronione-id-pytania-6199",
    isActive: true,
    id: "id6199",
    text: "Czy na drodze jednokierunkowej cofanie jest zabronione?",
    a: "",
    b: "",
    c: "",
    r: "n",
    media: "1A5416.png",
    categories: ["b", "c", "d", "t", "am", "b1", "c1", "d1"],
    score: 2,
  },
  {
    slug: "czy-skrecajac-w-lewo-na-tym-skrzyzowaniu-nalezy-zachowac-szczegolna-ostroznosc-id-pytania-8595",
    isActive: true,
    id: "id8595",
    text: "Czy skręcając w lewo na tym skrzyżowaniu należy zachować szczególną ostrożność?",
    a: "",
    b: "",
    c: "",
    r: "t",
    media: "PNS-10-14-0004_Censored_1024x576.mp4",
    categories: ["b"],
    score: 3,
  },
  {
    slug: "w-jaki-sposob-wolno-ci-przewozic-ladunek-w-przyczepie-ciagnietej-przez-samochod-osobowy-id-pytania-1877",
    isActive: true,
    id: "id1877",
    text: "W jaki sposób wolno Ci przewozić ładunek w przyczepie ciągniętej przez samochód osobowy?",
    a: "Ładunek może zasłaniać niektóre światła przyczepy.",
    b: "Ładunek nie może naruszać stateczności pojazdu.",
    c: "Ładunek nie musi być zabezpieczony przed zmianą położenia.",
    r: "b",
    media: "",
    categories: ["b"],
    score: 2,
  },
  {
    slug: "w-ktorym-z-wymienionych-przypadkow-masz-obowiazek-wymienic-opone-na-nowa-w-samochodzie-osobowym-id-pytania-10104",
    isActive: true,
    id: "id10104",
    text: "W którym z wymienionych przypadków, masz obowiązek wymienić oponę na nową w samochodzie osobowym?",
    a: "Gdy uszkodzony jest zawór powietrza.",
    b: "Gdy w czole opony znajduje się cienki gwóźdź.",
    c: "Gdy na boku opony są widoczne odkształcenia.",
    r: "c",
    media: "wymiana_kola_1024x576.png",
    categories: ["b"],
    score: 1,
  },
  {
    slug: "czy-predkosc-dopuszczalna-50-kmh-obowiazuje-na-obszarze-zabudowanym-przez-cala-dobe-id-pytania-12942",
    isActive: true,
    id: "id12942",
    text: "Czy prędkość dopuszczalna 50 km/h obowiązuje na obszarze zabudowanym przez całą dobę?",
    a: "Tak.",
    b: "Nie, tylko od godziny 5:00 do 23:00.",
    c: "Nie, tylko od zmierzchu do świtu.",
    r: "a",
    media: "Ba1_6011ztVpic.png",
    categories: ["b"],
    score: 3,
  },
  {
    slug: "ktora-z-widocznych-na-ilustracji-lampek-kontrolnych-sygnalizuje-niezapiete-pasy-bezpieczenstwa-id-pytania-9102",
    isActive: true,
    id: "id9102",
    text: "Która z widocznych na ilustracji lampek kontrolnych sygnalizuje niezapięte pasy bezpieczeństwa?",
    a: "A.",
    b: "B.",
    c: "C.",
    r: "b",
    media: "6007.png",
    categories: ["b"],
    score: 1,
  },
  {
    slug: "jaki-czynnik-powoduje-zmniejszenie-pola-widzenia-kierujacego-pojazdem-id-pytania-10069",
    isActive: true,
    id: "id10069",
    text: "Jaki czynnik powoduje zmniejszenie pola widzenia kierującego pojazdem?",
    a: "Duża prędkość jazdy.",
    b: "Dobra przejrzystość powietrza.",
    c: "Zbyt mała prędkość.",
    r: "a",
    media: "Slajd277_cen_1024x576.png",
    categories: ["b"],
    score: 2,
  },
  {
    slug: "w-ktorym-przypadku-nie-ma-obowiazku-przewozenia-dziecka-o-wzroscie-ponizej-150-cm-w-foteliku-bezpieczenstwa-lub-innym-urzadzeniu-podtrzymujacym-zapewniajacym-be-id-pytania-10990",
    isActive: true,
    id: "id10990",
    text: "W którym przypadku nie ma obowiązku przewożenia dziecka o wzroście poniżej 150 cm w foteliku bezpieczeństwa lub innym urządzeniu podtrzymującym, zapewniającym bezpieczeństwo dziecka?",
    a: "Podczas przewożenia dziecka taksówką.",
    b: "Podczas przewożenia dziecka na tylnym siedzeniu.",
    c: "Podczas przewożenia dziecka na kolanach osoby dorosłej.",
    r: "a",
    media: "",
    categories: ["b", "c", "d"],
    score: 3,
  },
  {
    slug: "jaki-dokument-jestes-zobowiazany-miec-przy-sobie-i-okazywac-na-zadanie-uprawnionego-organu-id-pytania-10895",
    isActive: true,
    id: "id10895",
    text: "Jaki dokument jesteś zobowiązany mieć przy sobie i okazywać na żądanie uprawnionego organu?",
    a: "Dokument potwierdzający uczestnictwo w kursie kwalifikacji wstępnej.",
    b: "Dokument stwierdzający uprawnienie do kierowania pojazdem inny niż wydane w kraju prawo jazdy.",
    c: "Dokument stwierdzający ukończenie kursu z pierwszej pomocy przedmedycznej.",
    r: "b",
    media: "",
    categories: ["b", "b1"],
    score: 3,
  },
  {
    slug: "jak-utrzymasz-wlasciwy-tor-jazdy-gdy-poruszasz-sie-droga-ekspresowa-w-gestej-mgle-id-pytania-6356",
    isActive: true,
    id: "id6356",
    text: "Jak utrzymasz właściwy tor jazdy, gdy poruszasz się drogą ekspresową w gęstej mgle?",
    a: "Uwzględniając znaki poziome wyznaczające pasy ruchu.",
    b: "Obserwując znaki pionowe.",
    c: "Obserwując wskazania nawigacji satelitarnej.",
    r: "a",
    media: "2B205.png",
    categories: ["b"],
    score: 3,
  },
  {
    slug: "jakie-sa-najistotniejsze-informacje-dla-sluzb-ratowniczych-okreslajace-miejsce-wypadku-drogowego-id-pytania-6454",
    isActive: true,
    id: "id6454",
    text: "Jakie są najistotniejsze informacje dla służb ratowniczych, określające miejsce wypadku drogowego?",
    a: "Nazwa ulicy i numer posesji lub numer drogi, nazwa najbliższej miejscowości, słupek kilometrowy.",
    b: "Numer telefonu informującego.",
    c: "Jedynie nazwa najbliższej miejscowości.",
    r: "a",
    media: "2D106.png",
    categories: ["b", "b1"],
    score: 3,
  },
  {
    slug: "ktora-z-wymienionych-czynnosci-jest-zabroniona-podczas-kierowania-pojazdem-id-pytania-7447",
    isActive: true,
    id: "id7447",
    text: "Która z wymienionych czynności jest zabroniona podczas kierowania pojazdem?",
    a: "Obsługiwanie radia.",
    b: "Używanie nawigacji GPS.",
    c: "Rozmawianie przez telefon, który wymaga trzymania słuchawki lub mikrofonu w ręku.",
    r: "c",
    media: "",
    categories: ["b", "b1"],
    score: 2,
  },
  {
    slug: "z-jaka-maksymalna-dopuszczalna-predkoscia-wolno-ci-kierowac-samochodem-osobowym-po-drodze-za-tym-znakiem-id-pytania-3618",
    isActive: true,
    id: "id3618",
    text: "Z jaką maksymalną dopuszczalną prędkością wolno Ci kierować samochodem osobowym po drodze za tym znakiem?",
    a: "70 km/h.",
    b: "100 km/h.",
    c: "90 km/h.",
    r: "c",
    media: "0978D14MM koniec obszaruorgbm.png",
    categories: ["b"],
    score: 3,
  },
  {
    slug: "jak-przewieziesz-ladunek-sypki-w-przyczepie-ciagnietej-przez-samochod-osobowy-id-pytania-1879",
    isActive: true,
    id: "id1879",
    text: "Jak przewieziesz ładunek sypki w przyczepie ciągniętej przez samochód osobowy?",
    a: "Niezasłonięty - umieszczony poniżej wysokości burt.",
    b: "Nie przekraczajac prędkości 30 km/h.",
    c: "Zasłonięty w szczelnej skrzyni ładunkowej.",
    r: "c",
    media: "",
    categories: ["b"],
    score: 2,
  },
];
